### ISSUE TITLE
Nice GUI!  💗 it and I'm sure visitors would love to see it in your readme too!

### ISSUE THREAD

**Issue by PySimpleGUI** [brraghav/simpleTools#1]
I'm a simple person.  There's few things more satisfying than seeing a GUI screenshot in the readme.  Short of that, incredibly satisfying is clicking "Copy File" from GitHub, pasting into PyCharm, clicking run, and instantly seeing a GUI:

![image](https://user-images.githubusercontent.com/46163555/154674017-ec517875-6015-426c-8ef7-85006e21a45a.png)

![image](https://user-images.githubusercontent.com/46163555/154674677-cbd6bef8-ed3d-4eda-bf56-836ed1fe7ce8.png)

YES!  Way to go.  That's how it should be.  Seconds from discovery to GUI on the screen.  SECONDS.  And you've made an attractive GUI.

To see it to your readme is actually trivial now that I simply pasted it into an Issue.  You can literally copy the line that my paste created and put into your readme file.

`![image](https://user-images.githubusercontent.com/46163555/154674017-ec517875-6015-426c-8ef7-85006e21a45a.png)
`

**Comment by PySimpleGUI** [comment]
Here is what your readme could appear for example
---------------------------

# simpleTools
This Repository is intended to create and maintain simple Tools that anyone can use without having to code. The tools can be as simple as extracting few keywords from text, but with lot of options and customizations.
Invoking the tools should be as simple as Double Clicking the Python files. Any extra requirements will be mentioned explicitly in the python files itself or an Usage example will be provided.

---------------------

## simpleLogFilter.py

![image](https://user-images.githubusercontent.com/46163555/154674017-ec517875-6015-426c-8ef7-85006e21a45a.png)
 

## Python Modules Installation

`pip install PySimpleGUI`

**Comment by brraghav** [comment]
Thank you @PySimpleGUI
I have updated Readme with the GUI of the tool.

**Comment by PySimpleGUI** [comment]
Very nice!  It looks great.  One image in a readme can make a world of difference.  Flipping through repos and seeing on, even when there is almost no text, grabs my attention immediately.

I'm hoping to get the Gallery feature into PySimpleGUI sooner than later to make these operations even easier to do.  In the meantime, you now know an easy trick using GitHub issues.  I've got a couple of "screenshot scratch pad" issues on GitHub where I store a ton of images that I use in documents, posts, tutorials, etc.  GitHub Issues have become my new image hosting service.  
![image](https://user-images.githubusercontent.com/46163555/154803992-13ebdf9b-5949-48fc-a1ad-d8c521e32db0.png)
